version: 1

accounts:
  - name: validatorv
    coins:
      - 1000000000000000uwolo

faucet:
  name: validatorv
  coins:
    - 500000000000uwolo

validators:
  - name: validatorv
    bonded: 500000000000000uwolo

client:
  openapi:
    path: docs/static/openapi.yml
